package com.example.KendyDigital.model.security;

/**
 * Canonical catalogue of security signals emitted across the platform.
 */
public enum SecurityEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGIN_UNKNOWN_EMAIL,
    ACCOUNT_LOCKED,
    TWO_FACTOR_FAILED,
    REVOKED_TOKEN_USED,
    SESSION_HIJACK_SUSPECTED,
    IMPOSSIBLE_TRAVEL,
    RATE_LIMITED,
    WAF_SQLI,
    WAF_XSS,
    WAF_TRAVERSAL,
    WAF_SCANNER,
    WAF_TOOL_USER_AGENT,
    HONEYTOKEN_HIT,
    ID_ENUMERATION,
    REGISTER_BURST,
    WEBHOOK_REJECTED,
    WEBHOOK_IP_NOT_ALLOWED,
    PRIVILEGE_CHANGE,
    TWO_FACTOR_DISABLED,
    PASSWORD_RESET,
    ACCOUNT_TAKEOVER_SUSPECTED,
    CREDENTIAL_REVEAL_BURST,
    COUPON_ABUSE,
    WARRANTY_ABUSE,
    BALANCE_MISMATCH,
    AUDIT_INTEGRITY_BROKEN,
    IP_BANNED,
    IP_UNBANNED
}
