--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account_credentials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account_credentials (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    delivered_at timestamp(6) with time zone,
    expires_at timestamp(6) with time zone,
    internal_note text,
    login_identifier character varying(255) NOT NULL,
    password_secret text NOT NULL,
    recovery_info text,
    status character varying(32) NOT NULL,
    two_factor_secret text,
    usage_note text,
    warranty_until timestamp(6) with time zone,
    assigned_order_id bigint,
    delivered_to_user_id bigint,
    service_id bigint NOT NULL,
    reserved_at timestamp(6) with time zone,
    reserved_until timestamp(6) with time zone,
    reserved_by_user_id bigint,
    reserved_checkout_id bigint,
    payload_hash character varying(128),
    CONSTRAINT account_credentials_status_check CHECK (((status)::text = ANY (ARRAY['AVAILABLE'::text, 'RESERVED'::text, 'DELIVERED'::text, 'REPLACED'::text, 'REFUNDED'::text, 'DISABLED'::text, 'EXPIRED'::text])))
);


--
-- Name: account_credentials_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.account_credentials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_credentials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admin_notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin_notifications (
    admin_user_id bigint,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    read_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone NOT NULL,
    message text,
    title character varying(200) NOT NULL
);


--
-- Name: admin_notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.admin_notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admin_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin_permissions (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    module character varying(32),
    code character varying(64) NOT NULL,
    description text
);


--
-- Name: admin_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.admin_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admin_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin_roles (
    system boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    description text,
    name character varying(50) NOT NULL
);


--
-- Name: admin_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.admin_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    actor_user_id bigint,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    target_id bigint,
    updated_at timestamp(6) with time zone NOT NULL,
    action character varying(100) NOT NULL,
    actor_role character varying(50),
    metadata text,
    target_type character varying(50),
    ip_address character varying(45)
);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_sessions (
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    last_used_at timestamp(6) with time zone,
    revoked_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL,
    token_hash character varying(64) NOT NULL
);


--
-- Name: auth_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bank_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bank_transactions (
    accumulated numeric(18,2),
    transfer_amount numeric(18,2),
    created_at timestamp(6) with time zone NOT NULL,
    credited_at timestamp(6) with time zone,
    id bigint NOT NULL,
    matched_deposit_request_id bigint,
    matched_user_id bigint,
    received_at timestamp(6) with time zone NOT NULL,
    sepay_id bigint,
    transaction_date timestamp(6) with time zone,
    updated_at timestamp(6) with time zone NOT NULL,
    wallet_transaction_id bigint,
    status character varying(32) NOT NULL,
    account_number character varying(30),
    bank_name character varying(100),
    code character varying(50),
    content text,
    gateway character varying(30),
    raw_payload text NOT NULL,
    reference_code character varying(100),
    review_reason character varying(500),
    sub_account character varying(50),
    transfer_type character varying(30),
    CONSTRAINT bank_transactions_status_check CHECK (((status)::text = ANY ((ARRAY['NEW'::character varying, 'MATCHED'::character varying, 'CREDITED'::character varying, 'DUPLICATE'::character varying, 'IGNORED'::character varying, 'MANUAL_REVIEW'::character varying, 'ERROR'::character varying])::text[])))
);


--
-- Name: bank_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bank_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: checkout_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.checkout_sessions (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    checkout_code character varying(50) NOT NULL,
    idempotency_key character varying(100),
    input_data text,
    status character varying(32) NOT NULL,
    deposit_request_id bigint NOT NULL,
    order_id bigint,
    service_id bigint NOT NULL,
    user_id bigint NOT NULL,
    status_message text,
    coupon_code character varying(50),
    discount_amount numeric(18,2),
    original_amount numeric(18,2),
    CONSTRAINT checkout_sessions_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING_PAYMENT'::character varying, 'PAID'::character varying, 'ORDER_CREATED'::character varying, 'EXPIRED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: checkout_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.checkout_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.checkout_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: content_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_items (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    content text,
    cta_url text,
    image_url text,
    published boolean NOT NULL,
    seo_description text,
    seo_title character varying(200),
    slug character varying(150) NOT NULL,
    sort_order integer NOT NULL,
    summary text,
    title character varying(200) NOT NULL,
    type character varying(32) NOT NULL,
    updated_by bigint,
    CONSTRAINT content_items_type_check CHECK (((type)::text = ANY ((ARRAY['BLOG'::character varying, 'STATIC_PAGE'::character varying, 'BANNER'::character varying, 'SITE_SECTION'::character varying, 'EMAIL_TEMPLATE'::character varying])::text[])))
);


--
-- Name: content_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.content_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.content_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: coupon_redemptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.coupon_redemptions (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    discount_amount numeric(18,2) NOT NULL,
    original_amount numeric(18,2) NOT NULL,
    payable_amount numeric(18,2) NOT NULL,
    coupon_id bigint NOT NULL,
    order_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: coupon_redemptions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.coupon_redemptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.coupon_redemptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: coupons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.coupons (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    admin_note text,
    code character varying(64) NOT NULL,
    ends_at timestamp(6) with time zone,
    max_discount_amount numeric(18,2),
    min_order_amount numeric(18,2),
    name character varying(100) NOT NULL,
    per_user_limit integer,
    starts_at timestamp(6) with time zone,
    status character varying(32) NOT NULL,
    type character varying(32) NOT NULL,
    usage_limit integer,
    used_count integer NOT NULL,
    service_id bigint,
    discount_value numeric(18,2) NOT NULL,
    CONSTRAINT coupons_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'DISABLED'::character varying])::text[]))),
    CONSTRAINT coupons_type_check CHECK (((type)::text = ANY ((ARRAY['PERCENT'::character varying, 'FIXED_AMOUNT'::character varying])::text[])))
);


--
-- Name: coupons_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.coupons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.coupons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: deposit_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.deposit_requests (
    amount numeric(18,2) NOT NULL,
    completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    expired_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    matched_bank_transaction_id bigint,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL,
    wallet_transaction_id bigint,
    status character varying(32) NOT NULL,
    bank_account character varying(30) NOT NULL,
    bank_name character varying(100) NOT NULL,
    bank_owner character varying(100) NOT NULL,
    deposit_code character varying(50) NOT NULL,
    transfer_content character varying(100) NOT NULL,
    CONSTRAINT deposit_requests_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'EXPIRED'::character varying, 'CANCELLED'::character varying, 'MANUAL_REVIEW'::character varying])::text[])))
);


--
-- Name: deposit_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.deposit_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deposit_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: email_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.email_logs (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    body text,
    error_message text,
    sent_at timestamp(6) with time zone,
    status character varying(32) NOT NULL,
    subject character varying(200) NOT NULL,
    to_email character varying(100) NOT NULL
);


--
-- Name: email_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.email_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.email_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: job_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.job_records (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    logs text,
    name character varying(100) NOT NULL,
    status character varying(255) NOT NULL
);


--
-- Name: job_records_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.job_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: manual_order_tasks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.manual_order_tasks (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    completed boolean NOT NULL,
    completed_at timestamp(6) with time zone,
    sort_order integer NOT NULL,
    title character varying(200) NOT NULL,
    completed_by_admin_id bigint,
    order_id bigint NOT NULL
);


--
-- Name: manual_order_tasks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.manual_order_tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.manual_order_tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_events (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    actor_role character varying(32),
    actor_user_id bigint,
    from_status character varying(32),
    note text,
    to_status character varying(32) NOT NULL,
    order_id bigint NOT NULL,
    CONSTRAINT order_events_from_status_check CHECK (((from_status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying])::text[]))),
    CONSTRAINT order_events_to_status_check CHECK (((to_status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying])::text[])))
);


--
-- Name: order_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orders (
    amount numeric(18,2) NOT NULL,
    cancelled_at timestamp(6) with time zone,
    completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    processing_at timestamp(6) with time zone,
    processing_deadline_at timestamp(6) with time zone,
    refund_transaction_id bigint,
    service_id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL,
    wallet_transaction_id bigint,
    status character varying(32) NOT NULL,
    admin_note text,
    idempotency_key character varying(100),
    input_data text,
    order_code character varying(50) NOT NULL,
    result_data text,
    user_note text,
    manual_checklist text,
    assigned_admin_id bigint,
    support_ticket_id bigint,
    coupon_code character varying(50),
    discount_amount numeric(18,2),
    original_amount numeric(18,2),
    deadline_overdue_notified_at timestamp(6) with time zone,
    deadline_reminder_sent_at timestamp(6) with time zone,
    manual_workflow_status character varying(32),
    CONSTRAINT orders_manual_workflow_status_check CHECK (((manual_workflow_status)::text = ANY ((ARRAY['NEW_REQUEST'::character varying, 'SCOPING'::character varying, 'WAITING_USER'::character varying, 'WAITING_PAYMENT'::character varying, 'IN_PROGRESS'::character varying, 'IN_REVIEW'::character varying, 'DONE'::character varying])::text[]))),
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying])::text[])))
);


--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.role_permissions (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    permission_id bigint NOT NULL,
    role_id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);


--
-- Name: role_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.role_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: service_categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.service_categories (
    sort_order integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    parent_id bigint,
    updated_at timestamp(6) with time zone NOT NULL,
    description text,
    name character varying(100) NOT NULL,
    slug character varying(120) NOT NULL,
    cta character varying(50),
    microcopy character varying(255),
    price_from character varying(50),
    processing_time character varying(100),
    requirements text,
    warranty character varying(100)
);


--
-- Name: service_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.service_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.services (
    cost_price numeric(18,2),
    featured boolean NOT NULL,
    price numeric(18,2) NOT NULL,
    public_visible boolean NOT NULL,
    sort_order integer NOT NULL,
    category_id bigint,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    cta_type character varying(32) NOT NULL,
    status character varying(32) NOT NULL,
    stock_status character varying(32) NOT NULL,
    type character varying(32) NOT NULL,
    benefits text,
    description text,
    icon_url character varying(500),
    input_schema text,
    meta_description text,
    meta_title character varying(200),
    name character varying(150) NOT NULL,
    price_text character varying(50),
    pricing_badge character varying(50),
    processing_time character varying(100),
    requirements text,
    short_description text,
    slug character varying(150) NOT NULL,
    usage_notes text,
    warranty_policy text,
    non_warranty_cases text,
    refund_policy text,
    risk_level character varying(16),
    usage_rules text,
    warranty_days integer,
    access_strategy character varying(32),
    access_duration_days integer,
    CONSTRAINT services_cta_type_check CHECK (((cta_type)::text = ANY ((ARRAY['BUY_NOW'::character varying, 'CONTACT'::character varying, 'CONSULT'::character varying])::text[]))),
    CONSTRAINT services_risk_level_check CHECK (((risk_level)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying, 'PROHIBITED'::character varying])::text[]))),
    CONSTRAINT services_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'ACTIVE'::character varying, 'INACTIVE'::character varying, 'MAINTENANCE'::character varying])::text[]))),
    CONSTRAINT services_stock_status_check CHECK (((stock_status)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'OUT_OF_STOCK'::character varying, 'CONSULTING_ONLY'::character varying])::text[])))
);


--
-- Name: services_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_import_batches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock_import_batches (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    imported_by bigint NOT NULL,
    notes text,
    quantity integer NOT NULL,
    service_id bigint NOT NULL
);


--
-- Name: stock_import_batches_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stock_import_batches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_import_batches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stored_files; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stored_files (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    size_bytes bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    uploaded_by bigint,
    content_type character varying(100),
    file_name character varying(255) NOT NULL,
    content oid
);


--
-- Name: stored_files_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stored_files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stored_files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: system_setting_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.system_setting_history (
    changed_by bigint,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    new_value text,
    old_value text,
    setting_key character varying(100) NOT NULL
);


--
-- Name: system_setting_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.system_setting_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.system_setting_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: system_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.system_settings (
    is_public boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by bigint,
    setting_key text NOT NULL,
    setting_value text
);


--
-- Name: ticket_attachments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ticket_attachments (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    size_bytes bigint,
    stored_file_id bigint,
    ticket_id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    content_type character varying(100),
    file_name character varying(255) NOT NULL
);


--
-- Name: ticket_attachments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ticket_attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ticket_attachments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ticket_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ticket_messages (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    sender_id bigint NOT NULL,
    ticket_id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    sender_role character varying(32) NOT NULL,
    attachments text,
    message text NOT NULL,
    CONSTRAINT ticket_messages_sender_role_check CHECK (((sender_role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying, 'SYSTEM'::character varying])::text[])))
);


--
-- Name: ticket_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ticket_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ticket_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tickets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tickets (
    assigned_admin_id bigint,
    closed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    deposit_request_id bigint,
    id bigint NOT NULL,
    order_id bigint,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL,
    category character varying(32) NOT NULL,
    priority character varying(32) NOT NULL,
    status character varying(32) NOT NULL,
    subject character varying(200) NOT NULL,
    ticket_code character varying(50) NOT NULL,
    CONSTRAINT tickets_category_check CHECK (((category)::text = ANY ((ARRAY['DEPOSIT'::character varying, 'ORDER'::character varying, 'ACCOUNT'::character varying, 'SERVICE'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT tickets_priority_check CHECK (((priority)::text = ANY ((ARRAY['LOW'::character varying, 'NORMAL'::character varying, 'HIGH'::character varying, 'URGENT'::character varying])::text[]))),
    CONSTRAINT tickets_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'PENDING_ADMIN'::character varying, 'PENDING_USER'::character varying, 'RESOLVED'::character varying, 'CLOSED'::character varying])::text[])))
);


--
-- Name: tickets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tickets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tickets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_admin_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_admin_roles (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    role_id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: user_admin_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_admin_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_admin_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_api_keys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_api_keys (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    last_used_at timestamp(6) with time zone,
    revoked_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL,
    key_prefix character varying(20) NOT NULL,
    key_hash character varying(64) NOT NULL,
    name character varying(100) NOT NULL,
    scopes text
);


--
-- Name: user_api_keys_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_api_keys ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_api_keys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_entitlements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_entitlements (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    service_id bigint NOT NULL,
    source_order_id bigint NOT NULL,
    access_strategy character varying(32) NOT NULL,
    status character varying(32) NOT NULL,
    access_identifier character varying(150),
    external_resource_id character varying(150),
    provider_metadata text,
    starts_at timestamp with time zone,
    expires_at timestamp with time zone,
    suspended_at timestamp with time zone,
    revoked_at timestamp with time zone,
    renewal_requested_at timestamp with time zone,
    last_error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: user_entitlements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.user_entitlements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: user_entitlements_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.user_entitlements_id_seq OWNED BY public.user_entitlements.id;


--
-- Name: user_favorite_services; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_favorite_services (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    service_id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: user_favorite_services_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_favorite_services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_favorite_services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_notification_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_notification_settings (
    deposit_updates boolean NOT NULL,
    email_notifications boolean NOT NULL,
    order_updates boolean NOT NULL,
    security_updates boolean NOT NULL,
    ticket_updates boolean NOT NULL,
    wallet_updates boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL,
    service_updates boolean
);


--
-- Name: user_notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_notifications (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    read_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL,
    type character varying(60),
    action_url character varying(500),
    message text,
    title character varying(200) NOT NULL
);


--
-- Name: user_notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_security_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_security_tokens (
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    used_at timestamp(6) with time zone,
    user_id bigint NOT NULL,
    type character varying(40) NOT NULL,
    token_hash character varying(64) NOT NULL,
    failed_attempts integer DEFAULT 0 NOT NULL,
    CONSTRAINT user_security_tokens_type_check CHECK (((type)::text = ANY ((ARRAY['PASSWORD_RESET'::character varying, 'PASSWORD_RESET_CONFIRMED'::character varying, 'EMAIL_VERIFICATION'::character varying, 'EMAIL_2FA'::character varying, 'OAUTH_2FA_CHALLENGE'::character varying])::text[])))
);


--
-- Name: user_security_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_security_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_security_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    balance numeric(18,2) NOT NULL,
    two_factor_enabled boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    email_verified_at timestamp(6) with time zone,
    id bigint NOT NULL,
    password_changed_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone NOT NULL,
    public_id uuid NOT NULL,
    role character varying(32) NOT NULL,
    status character varying(32) NOT NULL,
    admin_permissions text,
    avatar_url character varying(500),
    backup_codes text,
    email character varying(100) NOT NULL,
    name character varying(100) NOT NULL,
    oauth_provider character varying(50),
    oauth_provider_id character varying(100),
    password_hash character varying(100) NOT NULL,
    phone character varying(11),
    two_factor_secret text,
    locked_until timestamp(6) with time zone,
    failed_login_attempts integer DEFAULT 0 NOT NULL,
    locale character varying(10),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying, 'SUPER_ADMIN'::character varying])::text[]))),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'LOCKED'::character varying, 'PENDING_VERIFY'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wallet_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wallet_transactions (
    amount numeric(18,2) NOT NULL,
    balance_after numeric(18,2) NOT NULL,
    balance_before numeric(18,2) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by bigint,
    id bigint NOT NULL,
    reference_id bigint,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL,
    direction character varying(16) NOT NULL,
    type character varying(32) NOT NULL,
    description character varying(500),
    reference_type character varying(30),
    transaction_code character varying(50) NOT NULL,
    CONSTRAINT wallet_transactions_direction_check CHECK (((direction)::text = ANY ((ARRAY['CREDIT'::character varying, 'DEBIT'::character varying])::text[]))),
    CONSTRAINT wallet_transactions_type_check CHECK (((type)::text = ANY ((ARRAY['DEPOSIT'::character varying, 'PURCHASE'::character varying, 'REFUND'::character varying, 'ADMIN_ADJUST'::character varying, 'BONUS'::character varying, 'CORRECTION'::character varying])::text[])))
);


--
-- Name: wallet_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.wallet_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallet_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: warranty_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.warranty_requests (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    admin_note text,
    evidence_text text,
    reason text NOT NULL,
    resolved_at timestamp(6) with time zone,
    status character varying(32) NOT NULL,
    order_id bigint NOT NULL,
    original_credential_id bigint,
    refund_wallet_transaction_id bigint,
    replacement_credential_id bigint,
    user_id bigint NOT NULL,
    CONSTRAINT warranty_requests_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'REVIEWING'::character varying, 'APPROVED_REPLACE'::character varying, 'APPROVED_REFUND'::character varying, 'REJECTED'::character varying, 'RESOLVED'::character varying])::text[])))
);


--
-- Name: warranty_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.warranty_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.warranty_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_entitlements id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_entitlements ALTER COLUMN id SET DEFAULT nextval('public.user_entitlements_id_seq'::regclass);


--
-- Name: account_credentials account_credentials_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_credentials
    ADD CONSTRAINT account_credentials_pkey PRIMARY KEY (id);


--
-- Name: admin_notifications admin_notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_notifications
    ADD CONSTRAINT admin_notifications_pkey PRIMARY KEY (id);


--
-- Name: admin_permissions admin_permissions_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_permissions
    ADD CONSTRAINT admin_permissions_code_key UNIQUE (code);


--
-- Name: admin_permissions admin_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_permissions
    ADD CONSTRAINT admin_permissions_pkey PRIMARY KEY (id);


--
-- Name: admin_roles admin_roles_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_roles
    ADD CONSTRAINT admin_roles_name_key UNIQUE (name);


--
-- Name: admin_roles admin_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_roles
    ADD CONSTRAINT admin_roles_pkey PRIMARY KEY (id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: auth_sessions auth_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_sessions
    ADD CONSTRAINT auth_sessions_pkey PRIMARY KEY (id);


--
-- Name: bank_transactions bank_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_transactions
    ADD CONSTRAINT bank_transactions_pkey PRIMARY KEY (id);


--
-- Name: bank_transactions bank_transactions_wallet_transaction_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_transactions
    ADD CONSTRAINT bank_transactions_wallet_transaction_id_key UNIQUE (wallet_transaction_id);


--
-- Name: checkout_sessions checkout_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checkout_sessions
    ADD CONSTRAINT checkout_sessions_pkey PRIMARY KEY (id);


--
-- Name: content_items content_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_items
    ADD CONSTRAINT content_items_pkey PRIMARY KEY (id);


--
-- Name: coupon_redemptions coupon_redemptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coupon_redemptions
    ADD CONSTRAINT coupon_redemptions_pkey PRIMARY KEY (id);


--
-- Name: coupons coupons_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT coupons_pkey PRIMARY KEY (id);


--
-- Name: deposit_requests deposit_requests_matched_bank_transaction_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deposit_requests
    ADD CONSTRAINT deposit_requests_matched_bank_transaction_id_key UNIQUE (matched_bank_transaction_id);


--
-- Name: deposit_requests deposit_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deposit_requests
    ADD CONSTRAINT deposit_requests_pkey PRIMARY KEY (id);


--
-- Name: deposit_requests deposit_requests_wallet_transaction_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deposit_requests
    ADD CONSTRAINT deposit_requests_wallet_transaction_id_key UNIQUE (wallet_transaction_id);


--
-- Name: email_logs email_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_logs
    ADD CONSTRAINT email_logs_pkey PRIMARY KEY (id);


--
-- Name: job_records job_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_records
    ADD CONSTRAINT job_records_pkey PRIMARY KEY (id);


--
-- Name: manual_order_tasks manual_order_tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.manual_order_tasks
    ADD CONSTRAINT manual_order_tasks_pkey PRIMARY KEY (id);


--
-- Name: order_events order_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_events
    ADD CONSTRAINT order_events_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: orders orders_refund_transaction_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_refund_transaction_id_key UNIQUE (refund_transaction_id);


--
-- Name: orders orders_wallet_transaction_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_wallet_transaction_id_key UNIQUE (wallet_transaction_id);


--
-- Name: role_permissions role_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (id);


--
-- Name: service_categories service_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.service_categories
    ADD CONSTRAINT service_categories_pkey PRIMARY KEY (id);


--
-- Name: services services_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.services
    ADD CONSTRAINT services_pkey PRIMARY KEY (id);


--
-- Name: stock_import_batches stock_import_batches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_import_batches
    ADD CONSTRAINT stock_import_batches_pkey PRIMARY KEY (id);


--
-- Name: stored_files stored_files_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stored_files
    ADD CONSTRAINT stored_files_pkey PRIMARY KEY (id);


--
-- Name: system_setting_history system_setting_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.system_setting_history
    ADD CONSTRAINT system_setting_history_pkey PRIMARY KEY (id);


--
-- Name: system_settings system_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.system_settings
    ADD CONSTRAINT system_settings_pkey PRIMARY KEY (setting_key);


--
-- Name: ticket_attachments ticket_attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ticket_attachments
    ADD CONSTRAINT ticket_attachments_pkey PRIMARY KEY (id);


--
-- Name: ticket_messages ticket_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ticket_messages
    ADD CONSTRAINT ticket_messages_pkey PRIMARY KEY (id);


--
-- Name: tickets tickets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_pkey PRIMARY KEY (id);


--
-- Name: account_credentials uk_account_credentials_checkout; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_credentials
    ADD CONSTRAINT uk_account_credentials_checkout UNIQUE (reserved_checkout_id);


--
-- Name: account_credentials uk_account_credentials_order; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_credentials
    ADD CONSTRAINT uk_account_credentials_order UNIQUE (assigned_order_id);


--
-- Name: account_credentials uk_account_credentials_service_login; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_credentials
    ADD CONSTRAINT uk_account_credentials_service_login UNIQUE (service_id, login_identifier);


--
-- Name: account_credentials uk_account_credentials_service_payload_hash; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_credentials
    ADD CONSTRAINT uk_account_credentials_service_payload_hash UNIQUE (service_id, payload_hash);


--
-- Name: auth_sessions uk_auth_sessions_token_hash; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_sessions
    ADD CONSTRAINT uk_auth_sessions_token_hash UNIQUE (token_hash);


--
-- Name: bank_transactions uk_bank_transactions_reference; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_transactions
    ADD CONSTRAINT uk_bank_transactions_reference UNIQUE (reference_code);


--
-- Name: bank_transactions uk_bank_transactions_sepay_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_transactions
    ADD CONSTRAINT uk_bank_transactions_sepay_id UNIQUE (sepay_id);


--
-- Name: bank_transactions uk_bank_transactions_wallet_tx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_transactions
    ADD CONSTRAINT uk_bank_transactions_wallet_tx UNIQUE (wallet_transaction_id);


--
-- Name: checkout_sessions uk_checkout_sessions_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checkout_sessions
    ADD CONSTRAINT uk_checkout_sessions_code UNIQUE (checkout_code);


--
-- Name: checkout_sessions uk_checkout_sessions_deposit; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checkout_sessions
    ADD CONSTRAINT uk_checkout_sessions_deposit UNIQUE (deposit_request_id);


--
-- Name: checkout_sessions uk_checkout_sessions_order; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checkout_sessions
    ADD CONSTRAINT uk_checkout_sessions_order UNIQUE (order_id);


--
-- Name: checkout_sessions uk_checkout_sessions_user_idempotency; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checkout_sessions
    ADD CONSTRAINT uk_checkout_sessions_user_idempotency UNIQUE (user_id, idempotency_key);


--
-- Name: content_items uk_content_items_type_slug; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_items
    ADD CONSTRAINT uk_content_items_type_slug UNIQUE (type, slug);


--
-- Name: coupon_redemptions uk_coupon_redemptions_order; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coupon_redemptions
    ADD CONSTRAINT uk_coupon_redemptions_order UNIQUE (order_id);


--
-- Name: coupons uk_coupons_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT uk_coupons_code UNIQUE (code);


--
-- Name: deposit_requests uk_deposit_requests_bank_tx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deposit_requests
    ADD CONSTRAINT uk_deposit_requests_bank_tx UNIQUE (matched_bank_transaction_id);


--
-- Name: deposit_requests uk_deposit_requests_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deposit_requests
    ADD CONSTRAINT uk_deposit_requests_code UNIQUE (deposit_code);


--
-- Name: deposit_requests uk_deposit_requests_wallet_tx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deposit_requests
    ADD CONSTRAINT uk_deposit_requests_wallet_tx UNIQUE (wallet_transaction_id);


--
-- Name: user_entitlements uk_entitlements_source_order; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_entitlements
    ADD CONSTRAINT uk_entitlements_source_order UNIQUE (source_order_id);


--
-- Name: orders uk_orders_order_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT uk_orders_order_code UNIQUE (order_code);


--
-- Name: orders uk_orders_refund_tx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT uk_orders_refund_tx UNIQUE (refund_transaction_id);


--
-- Name: orders uk_orders_user_idempotency; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT uk_orders_user_idempotency UNIQUE (user_id, idempotency_key);


--
-- Name: orders uk_orders_wallet_tx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT uk_orders_wallet_tx UNIQUE (wallet_transaction_id);


--
-- Name: role_permissions uk_role_permission; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT uk_role_permission UNIQUE (role_id, permission_id);


--
-- Name: service_categories uk_service_categories_slug; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.service_categories
    ADD CONSTRAINT uk_service_categories_slug UNIQUE (slug);


--
-- Name: services uk_services_slug; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.services
    ADD CONSTRAINT uk_services_slug UNIQUE (slug);


--
-- Name: tickets uk_tickets_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT uk_tickets_code UNIQUE (ticket_code);


--
-- Name: user_admin_roles uk_user_admin_role; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_admin_roles
    ADD CONSTRAINT uk_user_admin_role UNIQUE (user_id, role_id);


--
-- Name: user_api_keys uk_user_api_keys_hash; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_api_keys
    ADD CONSTRAINT uk_user_api_keys_hash UNIQUE (key_hash);


--
-- Name: user_favorite_services uk_user_favorite_service; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_favorite_services
    ADD CONSTRAINT uk_user_favorite_service UNIQUE (user_id, service_id);


--
-- Name: user_security_tokens uk_user_security_tokens_hash; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_security_tokens
    ADD CONSTRAINT uk_user_security_tokens_hash UNIQUE (token_hash);


--
-- Name: users uk_users_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_email UNIQUE (email);


--
-- Name: users uk_users_public_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_public_id UNIQUE (public_id);


--
-- Name: wallet_transactions uk_wallet_transactions_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet_transactions
    ADD CONSTRAINT uk_wallet_transactions_code UNIQUE (transaction_code);


--
-- Name: warranty_requests uke13a94y43ecgxakdfyhtuqgup; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.warranty_requests
    ADD CONSTRAINT uke13a94y43ecgxakdfyhtuqgup UNIQUE (refund_wallet_transaction_id);


--
-- Name: orders ukp2gpoxhnphw07cyedj8pdf60v; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT ukp2gpoxhnphw07cyedj8pdf60v UNIQUE (support_ticket_id);


--
-- Name: user_admin_roles user_admin_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_admin_roles
    ADD CONSTRAINT user_admin_roles_pkey PRIMARY KEY (id);


--
-- Name: user_api_keys user_api_keys_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_api_keys
    ADD CONSTRAINT user_api_keys_pkey PRIMARY KEY (id);


--
-- Name: user_entitlements user_entitlements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_entitlements
    ADD CONSTRAINT user_entitlements_pkey PRIMARY KEY (id);


--
-- Name: user_favorite_services user_favorite_services_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_favorite_services
    ADD CONSTRAINT user_favorite_services_pkey PRIMARY KEY (id);


--
-- Name: user_notification_settings user_notification_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_notification_settings
    ADD CONSTRAINT user_notification_settings_pkey PRIMARY KEY (user_id);


--
-- Name: user_notifications user_notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_notifications
    ADD CONSTRAINT user_notifications_pkey PRIMARY KEY (id);


--
-- Name: user_security_tokens user_security_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_security_tokens
    ADD CONSTRAINT user_security_tokens_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: wallet_transactions wallet_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet_transactions
    ADD CONSTRAINT wallet_transactions_pkey PRIMARY KEY (id);


--
-- Name: warranty_requests warranty_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.warranty_requests
    ADD CONSTRAINT warranty_requests_pkey PRIMARY KEY (id);


--
-- Name: idx_account_credentials_order; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_account_credentials_order ON public.account_credentials USING btree (assigned_order_id);


--
-- Name: idx_account_credentials_reserved_until; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_account_credentials_reserved_until ON public.account_credentials USING btree (reserved_until);


--
-- Name: idx_account_credentials_service_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_account_credentials_service_status ON public.account_credentials USING btree (service_id, status);


--
-- Name: idx_account_credentials_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_account_credentials_user ON public.account_credentials USING btree (delivered_to_user_id);


--
-- Name: idx_admin_notifications_user_read; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_admin_notifications_user_read ON public.admin_notifications USING btree (admin_user_id, read_at);


--
-- Name: idx_audit_logs_action; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_logs_action ON public.audit_logs USING btree (action);


--
-- Name: idx_audit_logs_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_logs_created_at ON public.audit_logs USING btree (created_at);


--
-- Name: idx_auth_sessions_expires_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auth_sessions_expires_at ON public.auth_sessions USING btree (expires_at);


--
-- Name: idx_auth_sessions_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auth_sessions_user_id ON public.auth_sessions USING btree (user_id);


--
-- Name: idx_bank_transactions_received_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bank_transactions_received_at ON public.bank_transactions USING btree (received_at);


--
-- Name: idx_bank_transactions_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bank_transactions_status ON public.bank_transactions USING btree (status);


--
-- Name: idx_checkout_sessions_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_checkout_sessions_status ON public.checkout_sessions USING btree (status);


--
-- Name: idx_checkout_sessions_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_checkout_sessions_user_id ON public.checkout_sessions USING btree (user_id);


--
-- Name: idx_content_items_published; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_content_items_published ON public.content_items USING btree (published);


--
-- Name: idx_content_items_sort_order; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_content_items_sort_order ON public.content_items USING btree (sort_order);


--
-- Name: idx_content_items_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_content_items_type ON public.content_items USING btree (type);


--
-- Name: idx_coupon_redemptions_coupon_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_coupon_redemptions_coupon_user ON public.coupon_redemptions USING btree (coupon_id, user_id);


--
-- Name: idx_coupons_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_coupons_code ON public.coupons USING btree (code);


--
-- Name: idx_coupons_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_coupons_status ON public.coupons USING btree (status);


--
-- Name: idx_deposit_requests_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_deposit_requests_status ON public.deposit_requests USING btree (status);


--
-- Name: idx_deposit_requests_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_deposit_requests_user_id ON public.deposit_requests USING btree (user_id);


--
-- Name: idx_email_logs_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_email_logs_created_at ON public.email_logs USING btree (created_at);


--
-- Name: idx_email_logs_to_email; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_email_logs_to_email ON public.email_logs USING btree (to_email);


--
-- Name: idx_entitlements_expires_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_entitlements_expires_at ON public.user_entitlements USING btree (expires_at);


--
-- Name: idx_entitlements_external_resource; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_entitlements_external_resource ON public.user_entitlements USING btree (external_resource_id);


--
-- Name: idx_entitlements_user_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_entitlements_user_status ON public.user_entitlements USING btree (user_id, status);


--
-- Name: idx_job_records_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_job_records_status ON public.job_records USING btree (status);


--
-- Name: idx_manual_order_tasks_completed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_manual_order_tasks_completed ON public.manual_order_tasks USING btree (completed);


--
-- Name: idx_manual_order_tasks_order_sort; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_manual_order_tasks_order_sort ON public.manual_order_tasks USING btree (order_id, sort_order);


--
-- Name: idx_order_events_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_order_events_created_at ON public.order_events USING btree (created_at);


--
-- Name: idx_order_events_order_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_order_events_order_id ON public.order_events USING btree (order_id);


--
-- Name: idx_orders_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_orders_created_at ON public.orders USING btree (created_at);


--
-- Name: idx_orders_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_orders_status ON public.orders USING btree (status);


--
-- Name: idx_orders_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_orders_user_id ON public.orders USING btree (user_id);


--
-- Name: idx_role_permissions_role_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_role_permissions_role_id ON public.role_permissions USING btree (role_id);


--
-- Name: idx_service_categories_sort_order; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_service_categories_sort_order ON public.service_categories USING btree (sort_order);


--
-- Name: idx_services_category_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_services_category_id ON public.services USING btree (category_id);


--
-- Name: idx_services_featured; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_services_featured ON public.services USING btree (featured);


--
-- Name: idx_services_public_visible; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_services_public_visible ON public.services USING btree (public_visible);


--
-- Name: idx_services_sort_order; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_services_sort_order ON public.services USING btree (sort_order);


--
-- Name: idx_services_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_services_status ON public.services USING btree (status);


--
-- Name: idx_stock_import_batches_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stock_import_batches_created_at ON public.stock_import_batches USING btree (created_at);


--
-- Name: idx_stock_import_batches_service_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stock_import_batches_service_id ON public.stock_import_batches USING btree (service_id);


--
-- Name: idx_system_setting_history_key; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_system_setting_history_key ON public.system_setting_history USING btree (setting_key);


--
-- Name: idx_ticket_attachments_ticket_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ticket_attachments_ticket_id ON public.ticket_attachments USING btree (ticket_id);


--
-- Name: idx_ticket_messages_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ticket_messages_created_at ON public.ticket_messages USING btree (created_at);


--
-- Name: idx_ticket_messages_ticket_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ticket_messages_ticket_id ON public.ticket_messages USING btree (ticket_id);


--
-- Name: idx_tickets_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tickets_created_at ON public.tickets USING btree (created_at);


--
-- Name: idx_tickets_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tickets_status ON public.tickets USING btree (status);


--
-- Name: idx_tickets_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tickets_user_id ON public.tickets USING btree (user_id);


--
-- Name: idx_user_admin_roles_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_admin_roles_user_id ON public.user_admin_roles USING btree (user_id);


--
-- Name: idx_user_api_keys_key_prefix; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_api_keys_key_prefix ON public.user_api_keys USING btree (key_prefix);


--
-- Name: idx_user_api_keys_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_api_keys_user_id ON public.user_api_keys USING btree (user_id);


--
-- Name: idx_user_favorite_services_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_favorite_services_user_id ON public.user_favorite_services USING btree (user_id);


--
-- Name: idx_user_notifications_read_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_notifications_read_at ON public.user_notifications USING btree (read_at);


--
-- Name: idx_user_notifications_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_notifications_user_id ON public.user_notifications USING btree (user_id);


--
-- Name: idx_user_security_tokens_expires_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_security_tokens_expires_at ON public.user_security_tokens USING btree (expires_at);


--
-- Name: idx_user_security_tokens_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_security_tokens_type ON public.user_security_tokens USING btree (type);


--
-- Name: idx_user_security_tokens_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_security_tokens_user_id ON public.user_security_tokens USING btree (user_id);


--
-- Name: idx_users_oauth_provider; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_oauth_provider ON public.users USING btree (oauth_provider, oauth_provider_id);


--
-- Name: idx_users_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_status ON public.users USING btree (status);


--
-- Name: idx_wallet_transactions_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_wallet_transactions_created_at ON public.wallet_transactions USING btree (created_at);


--
-- Name: idx_wallet_transactions_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_wallet_transactions_user_id ON public.wallet_transactions USING btree (user_id);


--
-- Name: idx_wallet_transactions_user_type_direction; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_wallet_transactions_user_type_direction ON public.wallet_transactions USING btree (user_id, type, direction);


--
-- Name: idx_warranty_requests_order; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_warranty_requests_order ON public.warranty_requests USING btree (order_id);


--
-- Name: idx_warranty_requests_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_warranty_requests_status ON public.warranty_requests USING btree (status);


--
-- Name: idx_warranty_requests_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_warranty_requests_user ON public.warranty_requests USING btree (user_id);


--
-- Name: service_categories fk1lggon6dtecbuwkkf706i1a15; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.service_categories
    ADD CONSTRAINT fk1lggon6dtecbuwkkf706i1a15 FOREIGN KEY (parent_id) REFERENCES public.service_categories(id);


--
-- Name: user_favorite_services fk1v8h8uogqkf4s2mg04f9v1cg9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_favorite_services
    ADD CONSTRAINT fk1v8h8uogqkf4s2mg04f9v1cg9 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: orders fk32ql8ubntj5uh44ph9659tiih; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk32ql8ubntj5uh44ph9659tiih FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: ticket_messages fk3cdue8h4un44cfo9q4tq4mt4n; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ticket_messages
    ADD CONSTRAINT fk3cdue8h4un44cfo9q4tq4mt4n FOREIGN KEY (sender_id) REFERENCES public.users(id);


--
-- Name: deposit_requests fk483l7ifafrqodnbtjpgcpctmp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deposit_requests
    ADD CONSTRAINT fk483l7ifafrqodnbtjpgcpctmp FOREIGN KEY (matched_bank_transaction_id) REFERENCES public.bank_transactions(id);


--
-- Name: tickets fk4eqsebpimnjen0q46ja6fl2hl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT fk4eqsebpimnjen0q46ja6fl2hl FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: warranty_requests fk4s6puvoykm5r5fgrvtxhppeqe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.warranty_requests
    ADD CONSTRAINT fk4s6puvoykm5r5fgrvtxhppeqe FOREIGN KEY (original_credential_id) REFERENCES public.account_credentials(id);


--
-- Name: tickets fk4um0g3osslyegxhgywvn2xaxr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT fk4um0g3osslyegxhgywvn2xaxr FOREIGN KEY (assigned_admin_id) REFERENCES public.users(id);


--
-- Name: coupon_redemptions fk55hw3269sovxs2ftufcmflgtd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coupon_redemptions
    ADD CONSTRAINT fk55hw3269sovxs2ftufcmflgtd FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_admin_roles fk6irytmirjusdpm7j7q9vjjgkh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_admin_roles
    ADD CONSTRAINT fk6irytmirjusdpm7j7q9vjjgkh FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: checkout_sessions fk6m7fc42p68btvh3ywwyyryaxt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checkout_sessions
    ADD CONSTRAINT fk6m7fc42p68btvh3ywwyyryaxt FOREIGN KEY (deposit_request_id) REFERENCES public.deposit_requests(id);


--
-- Name: bank_transactions fk8bm09kcuwuc91gd0cy62gp3l0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_transactions
    ADD CONSTRAINT fk8bm09kcuwuc91gd0cy62gp3l0 FOREIGN KEY (matched_deposit_request_id) REFERENCES public.deposit_requests(id);


--
-- Name: ticket_messages fk8c9vw45c3j5m6arnwp4c3iaby; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ticket_messages
    ADD CONSTRAINT fk8c9vw45c3j5m6arnwp4c3iaby FOREIGN KEY (ticket_id) REFERENCES public.tickets(id);


--
-- Name: coupons fk8thejoyp3bus9ebmulepyobyq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT fk8thejoyp3bus9ebmulepyobyq FOREIGN KEY (service_id) REFERENCES public.services(id);


--
-- Name: bank_transactions fk97p056xudvdtbxqe9uu18jyvl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_transactions
    ADD CONSTRAINT fk97p056xudvdtbxqe9uu18jyvl FOREIGN KEY (wallet_transaction_id) REFERENCES public.wallet_transactions(id);


--
-- Name: user_notifications fk9f86wonnl11hos1cuf5fibutl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_notifications
    ADD CONSTRAINT fk9f86wonnl11hos1cuf5fibutl FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: orders fka4thenshyg6evufnuw4rcot9b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fka4thenshyg6evufnuw4rcot9b FOREIGN KEY (wallet_transaction_id) REFERENCES public.wallet_transactions(id);


--
-- Name: account_credentials fkacqvmf5iui8voay7tj2mfvqqi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_credentials
    ADD CONSTRAINT fkacqvmf5iui8voay7tj2mfvqqi FOREIGN KEY (delivered_to_user_id) REFERENCES public.users(id);


--
-- Name: role_permissions fkbb1hakngh5dan24fv0i1qnic1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT fkbb1hakngh5dan24fv0i1qnic1 FOREIGN KEY (permission_id) REFERENCES public.admin_permissions(id);


--
-- Name: deposit_requests fkbc7qx8clj1w05np5g0qr3djj6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deposit_requests
    ADD CONSTRAINT fkbc7qx8clj1w05np5g0qr3djj6 FOREIGN KEY (wallet_transaction_id) REFERENCES public.wallet_transactions(id);


--
-- Name: ticket_attachments fkddsdoqdixn4l34ssq1ndvk4wb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ticket_attachments
    ADD CONSTRAINT fkddsdoqdixn4l34ssq1ndvk4wb FOREIGN KEY (ticket_id) REFERENCES public.tickets(id);


--
-- Name: bank_transactions fkdm8p1rnk4if7muer3typjkbfn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_transactions
    ADD CONSTRAINT fkdm8p1rnk4if7muer3typjkbfn FOREIGN KEY (matched_user_id) REFERENCES public.users(id);


--
-- Name: manual_order_tasks fkdmn90vsvvg3bunnr8ok1y2n96; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.manual_order_tasks
    ADD CONSTRAINT fkdmn90vsvvg3bunnr8ok1y2n96 FOREIGN KEY (completed_by_admin_id) REFERENCES public.users(id);


--
-- Name: tickets fke21c7wbo6utu8nvjgqmx9rero; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT fke21c7wbo6utu8nvjgqmx9rero FOREIGN KEY (deposit_request_id) REFERENCES public.deposit_requests(id);


--
-- Name: warranty_requests fkew3i7qip9d3yq8l2ypxexddsv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.warranty_requests
    ADD CONSTRAINT fkew3i7qip9d3yq8l2ypxexddsv FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: services fkfffr4emayc2n4uq3yv618d9j0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.services
    ADD CONSTRAINT fkfffr4emayc2n4uq3yv618d9j0 FOREIGN KEY (category_id) REFERENCES public.service_categories(id);


--
-- Name: manual_order_tasks fkg2lsrd6tniw2soyjy1ov0m1ua; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.manual_order_tasks
    ADD CONSTRAINT fkg2lsrd6tniw2soyjy1ov0m1ua FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: warranty_requests fkglcr5fd2q3q4bbc0j6d8iad6c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.warranty_requests
    ADD CONSTRAINT fkglcr5fd2q3q4bbc0j6d8iad6c FOREIGN KEY (replacement_credential_id) REFERENCES public.account_credentials(id);


--
-- Name: checkout_sessions fkgr5xfsu4cw9oi3vvu3yrueq3w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checkout_sessions
    ADD CONSTRAINT fkgr5xfsu4cw9oi3vvu3yrueq3w FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: coupon_redemptions fkh7aunv3i22if0uql8581xtrhw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coupon_redemptions
    ADD CONSTRAINT fkh7aunv3i22if0uql8581xtrhw FOREIGN KEY (coupon_id) REFERENCES public.coupons(id);


--
-- Name: warranty_requests fkhmm5t8gu737iyq62cm4yucfk9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.warranty_requests
    ADD CONSTRAINT fkhmm5t8gu737iyq62cm4yucfk9 FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: account_credentials fkhtcm5986c51db3tiu5tv6spoj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_credentials
    ADD CONSTRAINT fkhtcm5986c51db3tiu5tv6spoj FOREIGN KEY (reserved_checkout_id) REFERENCES public.checkout_sessions(id);


--
-- Name: orders fkilhfy6s49sdt2q8dnh2ujpfdv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkilhfy6s49sdt2q8dnh2ujpfdv FOREIGN KEY (refund_transaction_id) REFERENCES public.wallet_transactions(id);


--
-- Name: checkout_sessions fkilsp21mgrq8ksn9a58usbwsne; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checkout_sessions
    ADD CONSTRAINT fkilsp21mgrq8ksn9a58usbwsne FOREIGN KEY (service_id) REFERENCES public.services(id);


--
-- Name: checkout_sessions fkj164pcmycdelqckwnyqa41me0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checkout_sessions
    ADD CONSTRAINT fkj164pcmycdelqckwnyqa41me0 FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: orders fkj4e3811h3jy9obp4uy8xxjb72; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkj4e3811h3jy9obp4uy8xxjb72 FOREIGN KEY (assigned_admin_id) REFERENCES public.users(id);


--
-- Name: orders fkj7bkj6q0u3681uv3bvq21316i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkj7bkj6q0u3681uv3bvq21316i FOREIGN KEY (service_id) REFERENCES public.services(id);


--
-- Name: role_permissions fkj9ww2qrvy3cr6pjxmx4i537fd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT fkj9ww2qrvy3cr6pjxmx4i537fd FOREIGN KEY (role_id) REFERENCES public.admin_roles(id);


--
-- Name: ticket_attachments fkjh181fex4lsbhtdy5etnsfshm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ticket_attachments
    ADD CONSTRAINT fkjh181fex4lsbhtdy5etnsfshm FOREIGN KEY (stored_file_id) REFERENCES public.stored_files(id);


--
-- Name: order_events fkjkqdh6opohx4rx9719gyn31aa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_events
    ADD CONSTRAINT fkjkqdh6opohx4rx9719gyn31aa FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: account_credentials fkjnomgqeepy4vprelwo7c2t1h9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_credentials
    ADD CONSTRAINT fkjnomgqeepy4vprelwo7c2t1h9 FOREIGN KEY (service_id) REFERENCES public.services(id);


--
-- Name: warranty_requests fkjyo3bxj2e9h7g32ygofxvpf5y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.warranty_requests
    ADD CONSTRAINT fkjyo3bxj2e9h7g32ygofxvpf5y FOREIGN KEY (refund_wallet_transaction_id) REFERENCES public.wallet_transactions(id);


--
-- Name: deposit_requests fkk1rpck9rstrgwf3hwp28pi76n; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deposit_requests
    ADD CONSTRAINT fkk1rpck9rstrgwf3hwp28pi76n FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: orders fkleh9o2hogypy5yyygkbeoxaal; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkleh9o2hogypy5yyygkbeoxaal FOREIGN KEY (support_ticket_id) REFERENCES public.tickets(id);


--
-- Name: coupon_redemptions fkn5pam1bg5g5ye2xfvntv57j0b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coupon_redemptions
    ADD CONSTRAINT fkn5pam1bg5g5ye2xfvntv57j0b FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: account_credentials fko7sp5rloethr1svk74skxmloo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_credentials
    ADD CONSTRAINT fko7sp5rloethr1svk74skxmloo FOREIGN KEY (reserved_by_user_id) REFERENCES public.users(id);


--
-- Name: account_credentials fkp0kp75a80oh0qosrsvt7554cx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_credentials
    ADD CONSTRAINT fkp0kp75a80oh0qosrsvt7554cx FOREIGN KEY (assigned_order_id) REFERENCES public.orders(id);


--
-- Name: user_security_tokens fkpg7rwlab5qwmtfe2w9sul7mep; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_security_tokens
    ADD CONSTRAINT fkpg7rwlab5qwmtfe2w9sul7mep FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: stock_import_batches fkphp22lu4mvn3u1drhs98vsum3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_import_batches
    ADD CONSTRAINT fkphp22lu4mvn3u1drhs98vsum3 FOREIGN KEY (service_id) REFERENCES public.services(id);


--
-- Name: auth_sessions fkpu507182mdfutajr71rgk67l; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_sessions
    ADD CONSTRAINT fkpu507182mdfutajr71rgk67l FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: tickets fkqgi3sbv1u45s41wawh75ut8ph; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT fkqgi3sbv1u45s41wawh75ut8ph FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: wallet_transactions fkrtsa3qtjhd0rn4xb92na03vd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet_transactions
    ADD CONSTRAINT fkrtsa3qtjhd0rn4xb92na03vd FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_api_keys fks49bj0ss79ya93wgj7k5synxc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_api_keys
    ADD CONSTRAINT fks49bj0ss79ya93wgj7k5synxc FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_notification_settings fks9tjvxu8ko31ivjlq9l9duh9y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_notification_settings
    ADD CONSTRAINT fks9tjvxu8ko31ivjlq9l9duh9y FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_admin_roles fksoac6ih83tqc9d9eja4t43ccr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_admin_roles
    ADD CONSTRAINT fksoac6ih83tqc9d9eja4t43ccr FOREIGN KEY (role_id) REFERENCES public.admin_roles(id);


--
-- Name: user_favorite_services fktbk93iumhwjvqffgdf3jhqwi5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_favorite_services
    ADD CONSTRAINT fktbk93iumhwjvqffgdf3jhqwi5 FOREIGN KEY (service_id) REFERENCES public.services(id);


--
-- Name: user_entitlements user_entitlements_service_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_entitlements
    ADD CONSTRAINT user_entitlements_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id);


--
-- Name: user_entitlements user_entitlements_source_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_entitlements
    ADD CONSTRAINT user_entitlements_source_order_id_fkey FOREIGN KEY (source_order_id) REFERENCES public.orders(id);


--
-- Name: user_entitlements user_entitlements_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_entitlements
    ADD CONSTRAINT user_entitlements_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

