-- V4: Security monitoring, threat detection and active response.
-- Adds security_events / security_alerts / ip_bans plus context columns on auth_sessions,
-- users and audit_logs.

-- ---------------------------------------------------------------------------
-- security_events
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.security_events (
    id bigint NOT NULL,
    occurred_at timestamp(6) with time zone NOT NULL,
    type character varying(64) NOT NULL,
    severity character varying(16) NOT NULL,
    ip character varying(45),
    asn character varying(64),
    country character varying(2),
    user_id bigint,
    session_id bigint,
    method character varying(10),
    path character varying(512),
    user_agent character varying(512),
    event_count integer DEFAULT 1 NOT NULL,
    fingerprint character varying(64),
    metadata text
);

ALTER TABLE public.security_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.security_events_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY public.security_events
    ADD CONSTRAINT security_events_pkey PRIMARY KEY (id);

CREATE INDEX IF NOT EXISTS idx_security_events_occurred_at ON public.security_events USING btree (occurred_at);
CREATE INDEX IF NOT EXISTS idx_security_events_type ON public.security_events USING btree (type);
CREATE INDEX IF NOT EXISTS idx_security_events_severity ON public.security_events USING btree (severity);
CREATE INDEX IF NOT EXISTS idx_security_events_ip ON public.security_events USING btree (ip);
CREATE INDEX IF NOT EXISTS idx_security_events_user_id ON public.security_events USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_security_events_fingerprint ON public.security_events USING btree (fingerprint);

-- ---------------------------------------------------------------------------
-- ip_bans
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ip_bans (
    id bigint NOT NULL,
    ip_or_cidr character varying(64) NOT NULL,
    reason character varying(255),
    source character varying(16) NOT NULL,
    rule_code character varying(32),
    created_by bigint,
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone,
    revoked_at timestamp(6) with time zone,
    revoked_by bigint,
    hit_count bigint DEFAULT 0 NOT NULL
);

ALTER TABLE public.ip_bans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ip_bans_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY public.ip_bans
    ADD CONSTRAINT ip_bans_pkey PRIMARY KEY (id);

CREATE INDEX IF NOT EXISTS idx_ip_bans_ip ON public.ip_bans USING btree (ip_or_cidr);
CREATE INDEX IF NOT EXISTS idx_ip_bans_expires_at ON public.ip_bans USING btree (expires_at);

-- ---------------------------------------------------------------------------
-- security_alerts
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.security_alerts (
    id bigint NOT NULL,
    rule_code character varying(32) NOT NULL,
    severity character varying(16) NOT NULL,
    title character varying(255) NOT NULL,
    subject_type character varying(16) NOT NULL,
    subject_value character varying(128) NOT NULL,
    first_seen timestamp(6) with time zone NOT NULL,
    last_seen timestamp(6) with time zone NOT NULL,
    event_count integer DEFAULT 1 NOT NULL,
    status character varying(16) NOT NULL,
    assignee character varying(255),
    note text,
    metadata text,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

ALTER TABLE public.security_alerts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.security_alerts_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY public.security_alerts
    ADD CONSTRAINT security_alerts_pkey PRIMARY KEY (id);

CREATE INDEX IF NOT EXISTS idx_security_alerts_status ON public.security_alerts USING btree (status);
CREATE INDEX IF NOT EXISTS idx_security_alerts_severity ON public.security_alerts USING btree (severity);
CREATE INDEX IF NOT EXISTS idx_security_alerts_last_seen ON public.security_alerts USING btree (last_seen);
CREATE INDEX IF NOT EXISTS idx_security_alerts_subject ON public.security_alerts USING btree (subject_type, subject_value);

-- ---------------------------------------------------------------------------
-- auth_sessions: session device/geo context
-- ---------------------------------------------------------------------------
ALTER TABLE public.auth_sessions ADD COLUMN IF NOT EXISTS created_ip character varying(45);
ALTER TABLE public.auth_sessions ADD COLUMN IF NOT EXISTS last_ip character varying(45);
ALTER TABLE public.auth_sessions ADD COLUMN IF NOT EXISTS user_agent character varying(512);
ALTER TABLE public.auth_sessions ADD COLUMN IF NOT EXISTS device_hash character varying(64);
ALTER TABLE public.auth_sessions ADD COLUMN IF NOT EXISTS country character varying(2);
ALTER TABLE public.auth_sessions ADD COLUMN IF NOT EXISTS asn character varying(64);

-- ---------------------------------------------------------------------------
-- users: last login context + 2FA throttling
-- ---------------------------------------------------------------------------
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS failed_two_factor_attempts integer DEFAULT 0 NOT NULL;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS two_factor_locked_until timestamp(6) with time zone;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS last_login_at timestamp(6) with time zone;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS last_login_ip character varying(45);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS last_login_country character varying(2);

-- ---------------------------------------------------------------------------
-- audit_logs: request context + tamper-evident hash chain
-- ---------------------------------------------------------------------------
ALTER TABLE public.audit_logs ADD COLUMN IF NOT EXISTS user_agent character varying(512);
ALTER TABLE public.audit_logs ADD COLUMN IF NOT EXISTS request_id character varying(64);
ALTER TABLE public.audit_logs ADD COLUMN IF NOT EXISTS prev_hash character varying(64);
ALTER TABLE public.audit_logs ADD COLUMN IF NOT EXISTS hash character varying(64);

CREATE INDEX IF NOT EXISTS idx_security_events_window
    ON public.security_events USING btree (occurred_at, type, ip);
